version: "3.8"
services:
  postgres:
    image: "postgres:15.1"
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - main_network
  # mongo:
  #   image: mongo:7.0
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: mongoadmin
  #     MONGO_INITDB_ROOT_PASSWORD: 12345
  #     MONGO_INITDB_ROOT_DATABASE: trinity
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - main_network
networks:
  main_network:
